defaults:
    - _self_

model:
    save_name: "./models/rf_regressor"
    pull_dvc: True

rf:
    criterion: "squared_error"
    n_estimators: 300

train_and_validate:
    test_size: 0.3

transformer:
    save_path: './models/transformer.joblib'

infer:
    file_for_predictions: "./data/all_rooms_combined.csv"
    save_path: "./data/predictions.csv"
    predict_share: 0.3